all:
  children:
    dwm:
      hosts:
        172.16.0.2:
      vars:
        ansible_user: alex
        timezone: Australia/Sydney
        ardour_repo: "https://github.com/Ardour/ardour.git"
        ardour_build_dir: "{{ ansible_env.HOME }}/ardour-build"
        vamp_build_dir: "{{ ansible_env.HOME }}/vamp-build"
        ardour_install_prefix: "/usr/local" 
